[package]
name = "test-helpers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
clock = { workspace = true, features = ["test-helpers"] }
delegate = { workspace = true }
eth = { workspace = true, features = ["test-helpers"] }
fuel-block-committer-encoding = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
metrics = { workspace = true }
mockall = { workspace = true }
ports = { workspace = true, features = ["full", "test-helpers"] }
rand = { workspace = true, features = ["small_rng"] }
services = { workspace = true, features = ["test-helpers"] }
storage = { workspace = true, features = ["test-helpers"] }
