[package]
name = "eth"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
alloy = { workspace = true, features = [
  "consensus",
  "network",
  "provider-ws",
  "kzg",
  "contract",
  "signer-aws",
  "signer-local",
  "rpc-types",
  "reqwest-rustls-tls",
] }
static_assertions = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true, features = ["default"] }
aws-sdk-kms = { workspace = true, features = ["default"] }
delegate = { workspace = true }
fuel-block-committer-encoding = { workspace = true, features = ["kzg"] }
futures = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
metrics = { workspace = true }
services = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }
url = { workspace = true }
trait-variant = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "fmt",
  "json",
] }
eth = { workspace = true, features = ["test-helpers"] }
alloy = { workspace = true, features = [
  "signer-local",
  "node-bindings",
  "json-rpc",
] }
serde_json = { workspace = true }
mockall = { workspace = true }
services = { workspace = true, features = ["test-helpers"] }
pretty_assertions = { workspace = true, features = ["default"] }
proptest = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["small_rng"] }
test-case = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[features]
test-helpers = []
