[package]
name = "signers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-kms = { workspace = true }
async-trait = { workspace = true }
k256 = { workspace = true, features = ["pkcs8"] }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
rust-eigenda-signers = { workspace = true }
thiserror = { workspace = true }

[features]
test-helpers = []
